### ISSUE TITLE
Arabic text support

### ISSUE THREAD

**Issue by knjl34** [dankito/RichTextEditor#29]
hi,

for Link text change?
How to proceed with arabic support ?

**Comment by dankito** [comment]
Hi knjl34,

sorry, I don't get you. What do you mean, what is the concrete issue?

Isn't anything working with HTML <a> elements, is there a problem with the Insert Link dialog, ...?

Could you provide a more specific description or a screenshot that shows the issue?

**Comment by knjl34** [comment]
> Hi knjl34,
> 
> sorry, I don't get you. What do you mean, what is the concrete issue?
> 
> Isn't anything working with HTML elements, is there a problem with the Insert Link dialog, ...?
> 
> Could you provide a more specific description or a screenshot that shows the issue?

Isn't anything working with HTML elements, is there a problem with the Insert Link dialog, ...?  === yes in arabic link dialog display in englis -- how to do that in arab. there is no res. in ar. so please add that in arabic or allow me to do that


thanks in advance.

**Comment by dankito** [comment]
Ah ok, then of course I can help you.

As I only speak a few words Arabic, could you provide these translations for me?

Go to the file [RichTextEditorAndroid/src/main/res/strings.xml](https://github.com/dankito/RichTextEditor/blob/master/RichTextEditorAndroid/src/main/res/values/strings.xml) .

Copy that to a folder named "values-ar" and provide translations for all keys that you need (if you like to I would be glad if you provide a translation for all of the keys).

If you like to allow your users to browse for images to insert, you would also have to provide translations for this file [https://github.com/dankito/AndroidFileChooserDialog/blob/master/FileChooserDialog/src/main/res/values/strings.xml](https://github.com/dankito/AndroidFileChooserDialog/blob/master/FileChooserDialog/src/main/res/values/strings.xml).

**Comment by knjl34** [comment]
i have changed that now one more help you can do is in link dialog whenever i have pressed ok after adding link please append this "http://" so in textview it will be clickable.

 like i have added google.com then convert it to be http://google.com so in textview it will auto click and goes to browser. 

thanx in advance.

**Comment by knjl34** [comment]
https://ibb.co/8ddbfPc

**Comment by knjl34** [comment]
> Ah ok, then of course I can help you.
> 
> As I only speak a few words Arabic, could you provide these translations for me?
> 
> Go to the file [RichTextEditorAndroid/src/main/res/strings.xml](https://github.com/dankito/RichTextEditor/blob/master/RichTextEditorAndroid/src/main/res/values/strings.xml) .
> 
> Copy that to a folder named "values-ar" and provide translations for all keys that you need (if you like to I would be glad if you provide a translation for all of the keys).
> 
> If you like to allow your users to browse for images to insert, you would also have to provide translations for this file https://github.com/dankito/AndroidFileChooserDialog/blob/master/FileChooserDialog/src/main/res/values/strings.xml.

Have you done commit changes ?

**Comment by dankito** [comment]
Which commit do you mean?

As I said, my Arabic is almost not existing, so you would have to provide these files / translations for me.

If you provide them to me, I'll be glad to commit and publish them.

**Comment by knjl34** [comment]
hi


<resources>

    <string name="dialog_edit_url_url_label">رابط الموقع</string>
    <string name="dialog_edit_url_title_label">عرض النص</string>

    <string name="dialog_edit_image_image_url_label">مسار الصورة أو عنوان الويب</string>
    <string name="dialog_edit_image_select_local_file">…</string>
    <string name="dialog_edit_image_alternate_text_label">نص بديل (اختياري)</string>
    <string name="dialog_edit_image_download_image_to_device">تحميل على الجهاز</string>
    <string name="dialog_edit_image_download_image_write_external_storage_rational">لحفظ الصورة خارج (غير مرئي) إذن مجلد التطبيق
        للكتابة إلى وحدة التخزين الخارجية.</string>

    <string name="dialog_select_text_color_title">اختيار لون النص</string>
    <string name="dialog_select_text_background_color_title">حدد لون خلفية النص</string>


    

    <string name="text_format_header_1"><![CDATA[
        <h1>Heading 1</h1>
    ]]></string>

    <string name="text_format_header_2"><![CDATA[
        <h2>Heading 2</h2>
    ]]></string>

    <string name="text_format_header_3"><![CDATA[
        <h3>Heading 3</h3>
    ]]></string>

    <string name="text_format_header_4"><![CDATA[
        <h4>Heading 4</h4>
    ]]></string>

    <string name="text_format_header_5"><![CDATA[
        <h5>Heading 5</h5>
    ]]></string>

    <string name="text_format_header_6"><![CDATA[
        <h6>Heading 6</h6>
    ]]></string>

    <string name="text_format_paragraph"><![CDATA[
        <p>Text body</p>
    ]]></string>

    <string name="text_format_preformat"><![CDATA[
        <pre><font face=\"courier\">Preformat</font></pre>
    ]]></string>

    <string name="text_format_block_quote"><![CDATA[
        <blockquote>Quote</blockquote>
    ]]></string>



    

    

    <string name="font_size_very_very_small"><![CDATA[
        <small><small><small>Teeny</small></small></small>
    ]]></string>

    <string name="font_size_very_small"><![CDATA[
        <small><small>Very small</small></small>
    ]]></string>

    <string name="font_size_small"><![CDATA[
        <small>Small</small>
    ]]></string>

    <string name="font_size_medium"><![CDATA[
        Medium
    ]]></string>

    <string name="font_size_large"><![CDATA[
        <big>Large</big>
    ]]></string>

    <string name="font_size_very_large"><![CDATA[
        <big><big>Very large</big></big>
    ]]></string>

    <string name="font_size_very_very_large"><![CDATA[
        <big><big><big>Huge</big></big></big>
    ]]></string>



    <string name="count_search_results_label" formatted="false">%d of %d</string>

</resources>



this are the string please add and commit it we need it in emergency basis and in link section please add https:// when in user enter any link so that link became clickable in textview.

thanks for the update and kind support.

**Comment by knjl34** [comment]
hey,

whenever do then please do this  in link section please add "https://" when in user enter any link so that link became clickable in text view.

**Comment by dankito** [comment]
Hey,

sorry, oversaw completely the 'http://' part.

Thought about it. I find it problematic for several reasons:
- Add 'http://' (your first proposal) or 'https://' (your second proposal)? RichTextEditor cannot know if for a specific url http or https is correct.
- Also add 'www.'? Most websites need that as well.
- I wouldn't silently add anything to the value the user entered. Some users would like to have exactly the same value as they entered and would be really angry about this dark magic (as there's no way to remove 'http://' again from link, RichTextEditor would insert it on each edit again).

So what do you think about that the default value entered is 'https://www.' and everything is selected by default, so that if the user doesn't like it, she/he can remove it with one click on Del button on keyboard?






If you think it's OK, I can release the new version in approximately an hour.

Your Arabic translation is highly appreciated and will be committed in a few minutes (on branch release/2.0.x).

And please no more "we need it in emergency basis" or similar. RichTextEditor is a non commercial open source software and I develop it entirely in my spare time, so I cannot always find time when somebody needs something. That's also a reason why you don't pay anything for it.

**Comment by knjl34** [comment]
hey ,

Yes that's also i can understand but we can archive it by condition basis like if itsn't contain then add else ignore ,

as i have already implemented and checked this type of scenario so  its really help full for developer purpose of the and its better to add that condition basis and in textview automatically it will be clickable so please do it in condition basis.

**Comment by dankito** [comment]
Sorry, what do you mean with "condition basis"?

The option to enter it by default in TextView and user can delete it or the dark magic option by silently adding 'http://'?

For the second option, a way to do this only in your application, would be to override `InsertLinkCommand` and there the method `executeCommand()`:

    override fun executeCommand(executor: JavaScriptExecutorBase) {
        selectLinkToInsert { url, title ->
            executor.insertLink(url, title)
        }
    }

Instead of calling `executor.insertLink(url, title)` directly implement you custom code there.

**Comment by knjl34** [comment]
hey ,

Yes that's also i can understand but we can archive it by condition basis like if itsn't contain then add else ignore ,

as i have already implemented and checked this type of scenario so  its really help full for developer purpose of the and its better to add that condition basis and in textview automatically it will be clickable so please do it in condition basis.

> I

this one will be fine so you can proceed for release !!

**Comment by dankito** [comment]
Released version 2.0.12 about an hour ago, but still cannot see it on Maven Central (Sonatype gave me some errors when uploading it, but should have worked).

Can you already see 2.0.12?

**Comment by dankito** [comment]
Now it's synchronized.

Check it out if it works for you and give me a feedback if not. (Otherwise feel free to close this issue.)

**Comment by knjl34** [comment]
hey,

its working perfect but for that dialog where http://www. are display in that dialog layout in ar, should be rtl, right now its display lrt,

rest of the things are working perfect Kudos,

Thanks.
